const projects = [
  { title: 'Group-Buying Platform', kind: 'Full-stack application', visual: 'buying', description: 'Built a platform where users discover store promotions, create purchase offers, and find others interested in joining the same group purchase.', detail: 'Designed a secure group-purchase workflow with payment and group-management features to help users coordinate purchases and reduce the risk of scams.', tags: ['Group purchases', 'Payment workflow', 'Group management'], github: 'https://github.com/medmedhaddioui/LetsBuyTogether' },
  { title: 'Kubernetes Infrastructure', kind: 'Infrastructure', date: 'Aug 2026 — Present', visual: 'cluster', description: 'Built a multi-node Kubernetes cluster using Vagrant, configuring both control-plane and worker nodes.', detail: 'Deployed and managed applications with Deployments, Services, ConfigMaps, and Ingress for traffic routing and application configuration.', tags: ['Kubernetes', 'K3s', 'Vagrant', 'Linux'], github: 'https://github.com/medmedhaddioui/IoT--42' },
  { title: 'Real-Time Multiplayer Game', kind: 'Real-time application', date: 'Sep 2025 — Nov 2025', visual: 'game', description: 'Built a real-time multiplayer platform using WebSockets, with a focus on maintaining low latency during live matches.', detail: 'Developed an automated tournament system with live scoring and rankings that update dynamically as matches are completed.', tags: ['Fastify', 'WebSocket', 'React', 'SQLite'], github: 'https://github.com/medmedhaddioui/ft_transcendence' },
]
function ProjectVisual({ type }) {
  if (type === 'game') return <img src="/pingpong.png" alt="Real-time multiplayer game interface" loading="lazy" />
  if (type === 'cluster') return <div className="cluster-diagram" role="img" aria-label="Kubernetes cluster diagram showing ingress, a control-plane node, and two workers"><span className="diagram-label">MULTI-NODE / K3s</span><div className="node ingress">Ingress</div><div className="connector"/><div className="node">Control plane</div><div className="connector"/><div className="workers"><div className="node">Worker 01<span>Pods · Services</span></div><div className="node">Worker 02<span>Pods · Services</span></div></div><span className="diagram-caption">VAGRANT + LINUX</span></div>
  return <img src="/letworkToghether.png" alt="LetsBuyTogether group-buying platform homepage" loading="lazy" />
}
export default function Projects() {
  return <section id="projects" className="section projects"><h2 className="section-heading"><span>03.</span> Some Things I’ve Built</h2><div className="featured-projects">{projects.map(project => <article className="featured-project" key={project.title}>
    <div className={`project-visual ${project.visual}`}><ProjectVisual type={project.visual}/></div>
    <div className="project-content"><p className="eyebrow">Featured Project</p><h3>{project.title}</h3><p className="project-date">{project.date || project.kind}</p><div className="project-description"><p>{project.description}</p><p>{project.detail}</p></div><ul className="project-tech">{project.tags.map(tag => <li key={tag}>{tag}</li>)}</ul>{project.github && <a className="project-source" href={project.github} target="_blank" rel="noreferrer" aria-label={`View source for ${project.title}`}>View source <span aria-hidden="true">↗</span></a>}</div>
  </article>)}</div><a className="text-link github-more" href="https://github.com/medmedhaddioui" target="_blank" rel="noreferrer">More on GitHub ↗</a></section>
}
